Fix typo causing NoMethodError in pmails view
Fixed @_organsation to @_organisation on line 14 of app/views/pmails/pmails.erb.
This typo caused the pmails method to be called on nil, resulting in the
NoMethodError: undefined method 'pmails' for nil:NilClass

Co-authored-by: Stephen Reid <stephenreid321@users.noreply.github.com>